/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cristian.morales' at '11/7/17 2:10 PM' with Gradle 2.14.1
 *
 * @author cristian.morales, @date 11/7/17 2:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
